### ISSUE TITLE
Too many extensions to Array and Enumerable isn't used elsewhere

### ISSUE THREAD

**Issue by lauritzthamsen** [LivelyKernel/LivelyKernel#12]
Interface of array feels quite big, with a couple of very similar functions. We even have some aliases...
If you count the function definitions in lively.lang.Array you'll get ridiculously close to 50...

Also, the _Enumerable_ object is created in lively.lang.Array and immediately mixed into the _Array.prototype_. I think that it's not used elsewhere - so we might skip this step as well in an effort to get a smaller Array interface...

**Comment by rksm** [comment]
with lively.lang a cleanup was done. we could still filter some extensions but the interface is mostly sane. https://github.com/LivelyKernel/lively.lang
