### ISSUE TITLE
Cannot save world to localhost

### ISSUE THREAD

**Issue by bertfreudenberg** [LivelyKernel/LivelyKernel#212]
[Visit issue world](http://lively-web.org/issues/14-01-12_Cannot_save_world_to_localhost.html)

reported by bert:

Tried to save a world from lively-web.org to http://localhost:9001/users/bert/xyz.html 
For one, it complains that the page exists already (it does not). After pressing okay, I get this error:

AttributeConnection>>update: Error: hostname differs in relativePathFrom http://localhost:9001/users/bert/Smalltalk-78.html vs http://lively-web.org/core/lively/bootstrap.jsstack:Error: hostname differs in relativePathFrom http://localhost:9001/users/bert/Smalltalk-78.html vs http://lively-web.org/core/lively/bootstrap.js    at URL.Object.subclass.relativePathFrom (http://lively-web.org/core/lively/Network.js:220:19)    at World.lively.morphic.World.addMethods.saveWorldAs (http://lively-web.org/core/lively/morphic/Serialization.js:256:48)    at http://lively-web.org/core/lively/morphic/Serialization.js:237:66    at ConfirmDialog.callback (http://lively-web.org/core/lively/morphic/Widgets.js:2761:18)    at ConfirmDialog.lively.morphic.App.subclass.triggerCallback (http://lively-web.org/core/lively/morphic/Widgets.js:2770:61)    at callOrSetTarget (http://lively-web.org/core/lively/bindings/Core.js:221:30)    at AttributeConnection.Object.subclass.update (http://lively-web.org/core/lively/bindings/Core.js:231:17)    at ConfirmDialog.result (http://lively-web.org/core/lively/bindings/Core.js:295:23)    at callOrSetTarget (http://lively-web.org/core/lively/bindings/Core.js:222:34)    at AttributeConnection.Object.subclass.update (http://lively-web.org/core/lively/bindings/Core.js:231:17)

**Comment by rksm** [comment]
as to the localhost issue: it is an open bug in Chrome https://code.google.com/p/chromium/issues/detail?id=67743

only way to get around it right now is to start chrome via --disable-web-security

We might consider saving worlds via Lively-2-Lively, though.

Closing for now.
