### ISSUE TITLE
Tools accept dropped morphs

### ISSUE THREAD

**Issue by bertfreudenberg** [LivelyKernel/LivelyKernel#303]
[Visit issue world](http://lively-web.org/issues/15-05-06_Tools_accept_dropped_morphs.html)

reported by bert:Tools like System Code Browser and Object Editor do not have dropping disabled. I often have my own morphs vanish because they get embedded accidentally in one of the tools.

**Comment by m-hemmings** [comment]
Issue resolved for System Code Browser and Object Editor
