### ISSUE TITLE
StyleEditorPane for Text morph: size slider has no effect

### ISSUE THREAD

**Issue by aranlunzer** [LivelyKernel/LivelyKernel#311]
A workaround is to move the slider, click on the updated number next to it, and press cmd-S.

Presumably there used to be some inter-object connection to automate this.

**Comment by m-hemmings** [comment]
Aran,
I have updated the connection from the slider to the text box on
lively-web.org so that it updates both the text string in the style editor
and the size of the text directly and Robert says he'll include it in his
next changes

Thanks,
-Matt Hemmings

**Comment by rksm** [comment]
:+1:
