### ISSUE TITLE
Install on a Raspberry PI2 running Debian fails

### ISSUE THREAD

**Issue by andyburnett** [LivelyKernel/LivelyKernel#315]
Node installs successfully, as does npm.
Git clone appears to put the files in the correct location. However, an npm install only gives one message

npm WARN package.json livelykernel@2.1.3 No license field.

Attempting to run lk server fails because lk cannot be found.

I also tried:

sudo curl http://lively-kernel.org/install.sh | sh

But that never got beyond 0%

**Comment by rksm** [comment]
Hi, Andy --

Sorry, those is the old pre-2013 install.  I recently installed Lively successfully using the instructions here: https://github.com/LivelyKernel/LivelyKernel/blob/master/README.md

All you need is node and then either a git checkout of the Lively repo or a zipped export via https://github.com/LivelyKernel/LivelyKernel/archive/master.zip if you don't want to install git.

Best,
Robert

**Comment by andyburnett** [comment]
Hi Robert,

That was definitely an improvement. However, when I run npm start I don't
end up with a working server. Instead I get the following error

[2015-12-10 01:50:44.181] [INFO] console - Reading 1, files in batch of
size 0B

[2015-12-10 01:50:44.188] [ERROR] console - file core/lib/ace/elm.snippets
has not content, skipping versioning it

[2015-12-10 01:50:44.200] [INFO] console - LivelyFsHandler registerWith done

**Comment by rksm** [comment]
Hmm, this error should not kill the server process... is the server still running? Does `curl -I HOSTNAME:9001` work? HOSTNAME will probably be localhost

**Comment by andyburnett** [comment]
Ah, now I see the problem. I hadn't realised that the server would only respond to localhost. I was trying to access the content via a browser on another machine.

curl -i localhost does work.
So, where do I change the setting so that the server is accessible beyond 127.0.0.1

**Comment by rksm** [comment]
Start the server via `node bin/lk-server.js --host 0.0.0.0 --port PORT`

**Comment by andyburnett** [comment]
Success! And, performance is not as bad as I had feared. Startup time is poor, but the system is quite useable after that.

Right, time to explore the LK ecosystem, and learn how to develop in it.
