### ISSUE TITLE
What is the world-menu?

### ISSUE THREAD

**Issue by Basilmir** [LivelyKernel/LivelyKernel#316]
Read something about lively kernel came to http://lively-web.org/ and after loading is done I arrive at http://lively-web.org/welcome.html

Lower down it says "To add new content, save an existing world with different name: World menu -> Save world as...." 

How can I access the world menu. I'm new to Lively kernel and already on the first page I'm told to use something and it doesn't tell me how.

**Comment by rksm** [comment]
Thanks for the feedback.  A world menu can be opened by right clicking into the background, I tried to improve the description on the welcome page a little.

**Comment by Basilmir** [comment]
Hmm... I was accessing the site on my tablet and I'm unable to right click. Single left click to the background was the initial solution in Smalltalk and later Squeak, and it always seemed awkward in the multi button windows world. From a design standpoint it's rather unusual to have 'no action' for left click on the background and 'world-menu' for second button click.

As a side note, the website isn't mobile friendly as Lively was conceived right at the start of the now 'mobile age'. I used to be very hard to implement anything that left click on any page but iOS 8 fixed that by adding improved gesture recognizers to Safari to make them available in web pages.

https://www.sitepen.com/blog/2011/12/07/touching-and-gesturing-on-iphone-android-and-more/

**Comment by rksm** [comment]
Yes, you are right, the Lively UI was not designed for touch interaction.  We had some experiments with it in the past but have not consistently mapped the UI functionality to touch gestures.  One challenge there is to allow both "app-level" and "meta-level" user interactions and customizations there of.  App-level is everyhing related to the thing you are building, meta-level the actions used to build.  In Lively we tried hard to stay away from modes and we would like to do so in the future.  For desktop interaction it works quite well using user enabled drag/dropping and menus as well as halos.  For touch interaction we need to experiment and specify what the mapping is supposed to be.  For example, most web apps use touch-and-drag for panning.  We currently have it mapped to dragging/grabbing objects.  These decisions need to be reviewed, extended and made consistent.

One experiment in the past was to add a "Bert-Button", that's the round thing with a Lively logo that appears only when you open a world on a touch device.  When you press it, e.g. with your thumb and then touch another object you will be able to open halos on that object.  The top-left halo opens the menu of a morph.  So, when you do that for the world (the background) you will be able to open the world menu and save.  Not really intuitive I agree.

**Comment by rksm** [comment]
touch experiments are on the way...
