### ISSUE TITLE
Login doesn't stick in Safe - Private Mode - Incognito browsing?

### ISSUE THREAD

**Issue by Basilmir** [LivelyKernel/LivelyKernel#317]
Most modern browsers offer a Safe or Private mode so you can navigate the web without websites having access to some data (other website cookies and so on).

The Lively page seems to have a problem with this and apparently logging in is impossible or doesn't stick when you click around the tutorial and it keeps asking for your name every time.

**Comment by rksm** [comment]
Hmm, you can use Lively without login, just saving stuff needs a user name.  You can login while still in incognito mode to save you just won't have the convenience of your user being remembered (we do this via a cookie).

**Comment by Basilmir** [comment]
You are right. However, the tutorial keeps on asking my name on every lesson page, I think because it tries to save my progress, this can probably be an undesired behaviour.

**Comment by Basilmir** [comment]
Added a some suggestions and a link.

**Comment by rksm** [comment]
Which tutorial do you mean?

And let me correct myself: The mode we use on lively-web.org stores the user name in localStorage, we have an optional server-side authentication mechanism that uses cookies but which isn't enabled for lively-web.org.

**Comment by rksm** [comment]
@Basilmir please let me know which tutorial and I will fix. Closing for now
