### ISSUE TITLE
can't get debugging feature work on a local copy of LK

### ISSUE THREAD

**Issue by ezhenezhen** [LivelyKernel/LivelyKernel#346]
Getting this kind of messages all the time when clicking on "debug next call". 
Any idea how to fix it?

Tried to load undefined.StackReification 4 times but failed. Giving up loading.
bootstrap.js:267 Tried to load undefined.Rewriting 4 times but failed. Giving up loading.
bootstrap.js:267 Tried to load undefined.AcornInterpreter 4 times but failed. Giving up loading.
bootstrap.js:267 loading module Global.lively.ide.codeeditor.JavaScriptDebugging timed out, trying again...
bootstrap.js:267 Tried to load undefined.StackReification 4 times but failed. Giving up loading.
bootstrap.js:267 Tried to load undefined.Rewriting 4 times but failed. Giving up loading.
bootstrap.js:267 Tried to load undefined.AcornInterpreter 4 times but failed. Giving up loading.

**Comment by rksm** [comment]
Sorry for that. We had some recent changes in our [lively.ast](https://github.com/LivelyKernel/lively.ast) package and I need to make sure that everything is wired up correctly in the github version. Code stepping on http://lively-web.org should work.

**Comment by rksm** [comment]
Sorry, took a while but it should work now.
