### ISSUE TITLE
Code rewriting breaks arithmetic

### ISSUE THREAD

**Issue by codefrau** [LivelyKernel/LivelyKernel#351]
I often use Lively as a JS workspace, but keep forgetting that this breaks:
```
Math.sqrt((1 - 2) ** 2 + (1 - 2) ** 2)
```

... because the precedence of `**` is not honored. 

Can we just make it an error, if we cannot fix it properly? A silently wrong result is worse than an error.

**Comment by rksm** [comment]
The newer version of escodegen should take care of that.
